version: '3.9'
services: 
  backend: 
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8000:8000
    volumes: 
      - .:/app

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'consumer.py'
    volumes:
      - .:/app

networks: 
  default: 
    external: 
      name: microservices_default